In [36]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [37]:
#data = pd.read_csv("KENET Combined data.csv")

In [38]:
#data.info()

In [39]:
#data.columns

In [40]:
data = pd.read_csv(r"C:\Users\Njula Chakaya\Downloads\KENET Combined data.csv")

In [41]:
#data.info()

In [42]:
data.head()

,ID,County,Total number of facilities,"Total number of facilities/ 10,000 population","Number of inpatient beds/ 10,000 population",Number of maternity beds/1000 pregnant women,Facility density score,Inpatient beds score,Maternity beds score,"Core health workforce / 10,000 population",...,Newborn health commodities Resuscitation equipment,Child health commodities Amoxicillin,Child health commodities Oral rehydration salts,Child health commodities Zinc sulphate,"Facility has record that shows individual pharmacy commodities received, disbursed, and balances",Facility has record that shows expired/unusable drugs being removed from inventory,Facility has Yellow PPB form (register or report form where adverse reactions are recorded),Facility has Pink PPB form (for recording substandard quality stock),Total number of facilities pharm reporting system,Pct Pharm Reporting
0,1,Baringo,63,2.9,10.4,7.7,147,41,77,10.6,...,0.11,0.68,0.90,0.88,0.98,0.69,0.27,0.45,54,0.857143
1,2,Bomet,56,1.5,8.8,7.6,76,35,76,8.9,...,0.08,0.24,0.94,0.87,0.94,0.71,0.31,0.59,53,0.946429
2,3,Bungoma,67,1.3,10.9,12.4,65,44,124,8.5,...,0.18,0.37,0.69,0.65,0.78,0.75,0.79,0.76,46,0.686567
3,4,Busia,56,1.6,14.3,18.0,79,57,180,11.9,...,0.27,0.55,0.90,0.92,0.87,0.71,0.63,0.74,48,0.857143
4,5,Elgeyo-marakwet,53,2.6,17.3,13.7,128,69,137,9.9,...,0.19,0.54,0.96,0.93,0.90,0.75,0.20,0.31,49,0.924528

In [43]:
data = data.drop(columns= 'ID', axis=1)
data.sample()

,County,Total number of facilities,"Total number of facilities/ 10,000 population","Number of inpatient beds/ 10,000 population",Number of maternity beds/1000 pregnant women,Facility density score,Inpatient beds score,Maternity beds score,"Core health workforce / 10,000 population",Health workforce density score,...,Newborn health commodities Resuscitation equipment,Child health commodities Amoxicillin,Child health commodities Oral rehydration salts,Child health commodities Zinc sulphate,"Facility has record that shows individual pharmacy commodities received, disbursed, and balances",Facility has record that shows expired/unusable drugs being removed from inventory,Facility has Yellow PPB form (register or report form where adverse reactions are recorded),Facility has Pink PPB form (for recording substandard quality stock),Total number of facilities pharm reporting system,Pct Pharm Reporting
38,Taita taveta,49,3.3,14.4,18.1,165,58,181,19.1,83,...,0.24,0.73,0.93,0.74,0.83,0.61,0.44,0.44,43,0.877551

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Columns: 112 entries, County to Pct Pharm Reporting
dtypes: float64(102), int64(9), object(1)
memory usage: 41.3+ KB

In [45]:
# Normalizing the data
df = data.select_dtypes(include=['float64', 'int64'])

scaler = MinMaxScaler()

data_norm = scaler.fit_transform(df)

data_norm = pd.DataFrame(data_norm, columns = df.columns)

data_norm.sample()

,Total number of facilities,"Total number of facilities/ 10,000 population","Number of inpatient beds/ 10,000 population",Number of maternity beds/1000 pregnant women,Facility density score,Inpatient beds score,Maternity beds score,"Core health workforce / 10,000 population",Health workforce density score,Haemoglobin,...,Newborn health commodities Resuscitation equipment,Child health commodities Amoxicillin,Child health commodities Oral rehydration salts,Child health commodities Zinc sulphate,"Facility has record that shows individual pharmacy commodities received, disbursed, and balances",Facility has record that shows expired/unusable drugs being removed from inventory,Facility has Yellow PPB form (register or report form where adverse reactions are recorded),Facility has Pink PPB form (for recording substandard quality stock),Total number of facilities pharm reporting system,Pct Pharm Reporting
17,0.745455,0.538462,0.263374,0.275081,0.532995,0.268041,0.275081,0.339161,0.344,0.210526,...,0.333333,0.470588,1.0,0.871795,0.525424,0.228916,0.073171,0.088608,0.771429,0.868571

In [46]:
# Define the reference vector as 1 for all indicators
n_indicators = 111
X_star = np.ones(n_indicators)

In [47]:
# Define the fuzzification constant of k
k = 1

In [48]:
# Calculate the fuzzy metric of each indicator
M = np.zeros((47,111))

for j in range (111):
    M[:, j] = k * X_star[j] / (k * X_star[j] + abs(data_norm.iloc[:, j] - X_star[j]))

In [49]:
# Calculate the composite fuzzy indicator for each observation 
CFI = np.prod(M, axis=1) ** (1/111)

In [50]:
# Create dataframe with the CFI
CFI = pd.DataFrame(CFI, columns= ['CFI']) 

CFI_data = pd.concat([data.select_dtypes(include= 'object'), CFI], axis=1)

CFI_data['CFI Rank'] =  CFI_data['CFI'].rank(ascending=False)

CFI_data = CFI_data.sort_values('CFI', ascending=False)

CFI_data

             County       CFI  CFI Rank
34        Nyandarua  0.740669       1.0
29          Nairobi  0.733436       2.0
36          Samburu  0.723254       3.0
12           Kiambu  0.714138       4.0
16           Kisumu  0.707624       5.0
35            Nyeri  0.702269       6.0
24         Marsabit  0.699099       7.0
30           Nakuru  0.694133       8.0
38     Taita taveta  0.687767       9.0
27          Mombasa  0.685547      10.0
18            Kwale  0.684049      11.0
28         Murang'a  0.683855      12.0
8            Isiolo  0.681423      13.0
19         Laikipia  0.678937      14.0
9           Kajiado  0.678347      15.0
22          Makueni  0.677852      16.0
43      Uasin gishu  0.671954      17.0
40    Tharaka-nithi  0.670791      18.0
15            Kisii  0.669544      19.0
1             Bomet  0.664274      20.0
17            Kitui  0.664244      21.0
37            Siaya  0.663471      22.0
7          Homa bay  0.659586      23.0
13           Kilifi  0.657481      24.0
10         Kakamega  0.656831      25.0
3             Busia  0.656094      26.0
20             Lamu  0.651899      27.0
32            Narok  0.650553      28.0
21         Machakos  0.649437      29.0
5              Embu  0.644048      30.0
6           Garissa  0.643643      31.0
33          Nyamira  0.642836      32.0
23          Mandera  0.642020      33.0
0           Baringo  0.641170      34.0
14        Kirinyaga  0.636535      35.0
44           Vihiga  0.630395      36.0
2           Bungoma  0.629313      37.0
26           Migori  0.627134      38.0
42          Turkana  0.624488      39.0
11          Kericho  0.623683      40.0
31            Nandi  0.618901      41.0
39       Tana river  0.615047      42.0
25             Meru  0.611271      43.0
4   Elgeyo-marakwet  0.609765      44.0
46       West pokot  0.605424      45.0
41      Trans nzoia  0.602025      46.0
45            Wajir  0.587989      47.0

In [52]:
# Composite Indicator using PCA
gsa = pd.read_csv("Merged GSA.csv")
gsr = pd.read_csv("Merged GSR.csv")

In [53]:
gsa = gsa.drop(columns=['Unnamed: 0', 'County'] ,axis=1)

In [54]:
gsa.shape

(47, 40)

In [55]:
gsr = gsr.drop(columns=['Unnamed: 0', 'County'], axis=1)

In [56]:
gsr.shape

(47, 72)

In [57]:
# Gsr Score
gsr_norm = scaler.fit_transform(gsr) # Normalize data

pca = PCA(1)

gsr_pca = pca.fit_transform(gsr_norm)

gsr_score = np.dot(gsr_norm, pca.components_.transpose())

gsr_score = pd.DataFrame(gsr_score, columns = ['GSR Score'])

gsr_score.head()

   GSR Score
0   2.317949
1   2.857726
2   1.638597
3   2.003508
4   1.569731

In [58]:
#GSA Score
gsa_norm = scaler.fit_transform(gsa) # Normalize data

pca = PCA(1)

gsa_pca = pca.fit_transform(gsa_norm)

gsa_score = np.dot(gsa_norm, pca.components_.transpose())

gsa_score = pd.DataFrame(gsa_score, columns = ['GSA Score'])

gsa_score.head()

   GSA Score
0   1.159683
1   2.556193
2   1.433902
3   1.616376
4   0.974819

In [59]:
# Get the weights of the each indicator
gsr_weight = len(gsr.columns)/len(df.columns)
gsa_weight = len(gsa.columns)/len(df.columns)

print("GSR Weight:", gsr_weight)
print("GSA Weight:", gsa_weight)

GSR Weight: 0.6486486486486487
GSA Weight: 0.36036036036036034

In [60]:
# Generate the Index
combination = pd.concat([gsr_score, gsa_score], axis = 1)

for i in combination:
    combination["Index"] = ((gsr_weight * combination['GSR Score']) + gsa_weight * combination['GSA Score'])

combination.head()

   GSR Score  GSA Score     Index
0   2.317949   1.159683  1.921438
1   2.857726   2.556193  2.774810
2   1.638597   1.433902  1.579595
3   2.003508   1.616376  1.882051
4   1.569731   0.974819  1.369490

In [61]:
PCA_Index = pd.concat([data.select_dtypes(include= 'object'), combination['Index']], axis=1)

PCA_Index['PCA Rank'] =  PCA_Index['Index'].rank(ascending=False)

PCA_Index = PCA_Index.sort_values('Index', ascending=False)

PCA_Index

             County     Index  PCA Rank
29          Nairobi  4.324399       1.0
35            Nyeri  4.279668       2.0
12           Kiambu  4.083583       3.0
34        Nyandarua  3.960190       4.0
28         Murang'a  3.421260       5.0
30           Nakuru  3.405589       6.0
27          Mombasa  3.346246       7.0
9           Kajiado  3.159066       8.0
16           Kisumu  3.085669       9.0
40    Tharaka-nithi  3.029893      10.0
36          Samburu  2.995468      11.0
24         Marsabit  2.966133      12.0
14        Kirinyaga  2.870908      13.0
38     Taita taveta  2.869853      14.0
18            Kwale  2.787110      15.0
43      Uasin gishu  2.781739      16.0
1             Bomet  2.774810      17.0
19         Laikipia  2.773563      18.0
21         Machakos  2.760952      19.0
17            Kitui  2.742110      20.0
22          Makueni  2.691225      21.0
5              Embu  2.574251      22.0
25             Meru  2.572319      23.0
13           Kilifi  2.553197      24.0
37            Siaya  2.360076      25.0
23          Mandera  2.321980      26.0
6           Garissa  2.310537      27.0
15            Kisii  2.255292      28.0
20             Lamu  2.206423      29.0
8            Isiolo  2.145248      30.0
10         Kakamega  2.108839      31.0
11          Kericho  2.026611      32.0
7          Homa bay  2.002660      33.0
32            Narok  1.931700      34.0
0           Baringo  1.921438      35.0
31            Nandi  1.882692      36.0
3             Busia  1.882051      37.0
44           Vihiga  1.843378      38.0
41      Trans nzoia  1.767047      39.0
33          Nyamira  1.735102      40.0
26           Migori  1.594574      41.0
2           Bungoma  1.579595      42.0
42          Turkana  1.556233      43.0
39       Tana river  1.405773      44.0
4   Elgeyo-marakwet  1.369490      45.0
46       West pokot  1.331486      46.0
45            Wajir  1.180784      47.0

In [62]:
PCA_Index.to_csv("PCA Index.csv")
CFI_data.to_csv("CFI.csv")

In [63]:
# Arithmetic average rank
average = data_norm.mean(axis = 1)

Avg_Index = pd.concat([data.select_dtypes(include= 'object'), average], axis=1)

Avg_Index = Avg_Index.rename(columns={0: 'Average'})

Avg_Index['Average Rank'] = Avg_Index['Average'].rank(ascending=False)

Avg_Index = Avg_Index.sort_values('Average', ascending=False)

Avg_Index

             County   Average  Average Rank
34        Nyandarua  0.618361           1.0
29          Nairobi  0.610261           2.0
36          Samburu  0.584741           3.0
12           Kiambu  0.578419           4.0
16           Kisumu  0.573219           5.0
30           Nakuru  0.543407           6.0
35            Nyeri  0.543381           7.0
24         Marsabit  0.527179           8.0
38     Taita taveta  0.523707           9.0
27          Mombasa  0.516079          10.0
18            Kwale  0.512756          11.0
9           Kajiado  0.508877          12.0
28         Murang'a  0.506693          13.0
19         Laikipia  0.504765          14.0
8            Isiolo  0.502854          15.0
22          Makueni  0.502198          16.0
43      Uasin gishu  0.495478          17.0
15            Kisii  0.485727          18.0
40    Tharaka-nithi  0.480405          19.0
17            Kitui  0.472870          20.0
37            Siaya  0.469606          21.0
1             Bomet  0.462919          22.0
7          Homa bay  0.460710          23.0
10         Kakamega  0.459481          24.0
13           Kilifi  0.456607          25.0
3             Busia  0.454459          26.0
21         Machakos  0.446065          27.0
20             Lamu  0.436925          28.0
32            Narok  0.432156          29.0
6           Garissa  0.427037          30.0
5              Embu  0.422259          31.0
33          Nyamira  0.416806          32.0
23          Mandera  0.415136          33.0
0           Baringo  0.414976          34.0
14        Kirinyaga  0.403603          35.0
44           Vihiga  0.389884          36.0
2           Bungoma  0.385894          37.0
26           Migori  0.382868          38.0
11          Kericho  0.380621          39.0
42          Turkana  0.363720          40.0
31            Nandi  0.360609          41.0
39       Tana river  0.347892          42.0
25             Meru  0.346354          43.0
4   Elgeyo-marakwet  0.336863          44.0
46       West pokot  0.324847          45.0
41      Trans nzoia  0.319880          46.0
45            Wajir  0.281976          47.0

In [64]:
import numpy as np
data2 = data_norm + 1e-6

geometric_averages = np.prod(data2, axis=1) ** (1 / len(data2.columns))

geometric_averages = pd.concat([data.select_dtypes(include= 'object'), geometric_averages], axis=1)

geometric_averages = geometric_averages.rename(columns={0: 'Geo Average'})

geometric_averages['Geo Average Rank'] = geometric_averages['Geo Average'].rank(ascending=False)

geometric_averages = geometric_averages.sort_values('Geo Average', ascending=False)

geometric_averages

             County  Geo Average  Geo Average Rank
16           Kisumu     0.431412               1.0
29          Nairobi     0.422918               2.0
12           Kiambu     0.408400               3.0
30           Nakuru     0.401113               4.0
43      Uasin gishu     0.399935               5.0
10         Kakamega     0.392971               6.0
27          Mombasa     0.387596               7.0
15            Kisii     0.378692               8.0
9           Kajiado     0.370592               9.0
38     Taita taveta     0.367580              10.0
36          Samburu     0.314932              11.0
34        Nyandarua     0.314332              12.0
22          Makueni     0.302017              13.0
6           Garissa     0.285847              14.0
19         Laikipia     0.264515              15.0
37            Siaya     0.264095              16.0
21         Machakos     0.261406              17.0
17            Kitui     0.260454              18.0
28         Murang'a     0.260338              19.0
8            Isiolo     0.244359              20.0
35            Nyeri     0.233862              21.0
1             Bomet     0.227665              22.0
18            Kwale     0.226737              23.0
40    Tharaka-nithi     0.223852              24.0
0           Baringo     0.211096              25.0
24         Marsabit     0.207123              26.0
7          Homa bay     0.203755              27.0
3             Busia     0.202129              28.0
32            Narok     0.192219              29.0
33          Nyamira     0.184115              30.0
11          Kericho     0.183101              31.0
13           Kilifi     0.178321              32.0
2           Bungoma     0.158873              33.0
26           Migori     0.155872              34.0
44           Vihiga     0.134347              35.0
14        Kirinyaga     0.121560              36.0
5              Embu     0.113720              37.0
23          Mandera     0.107999              38.0
4   Elgeyo-marakwet     0.091152              39.0
25             Meru     0.087573              40.0
20             Lamu     0.081541              41.0
31            Nandi     0.080365              42.0
41      Trans nzoia     0.065100              43.0
46       West pokot     0.064435              44.0
39       Tana river     0.059729              45.0
42          Turkana     0.030287              46.0
45            Wajir     0.028230              47.0

In [65]:
# Comparing the results
merged_results = pd.merge(CFI_data, PCA_Index, on='County')

merged_results = pd.merge(merged_results, Avg_Index, on='County')

merged_results = pd.merge(merged_results, geometric_averages)

merged_results

,County,CFI,CFI Rank,Index,PCA Rank,Average,Average Rank,Geo Average,Geo Average Rank
0,Nyandarua,0.740669,1.0,3.960190,4.0,0.618361,1.0,0.314332,12.0
1,Nairobi,0.733436,2.0,4.324399,1.0,0.610261,2.0,0.422918,2.0
2,Samburu,0.723254,3.0,2.995468,11.0,0.584741,3.0,0.314932,11.0
3,Kiambu,0.714138,4.0,4.083583,3.0,0.578419,4.0,0.408400,3.0
4,Kisumu,0.707624,5.0,3.085669,9.0,0.573219,5.0,0.431412,1.0
5,Nyeri,0.702269,6.0,4.279668,2.0,0.543381,7.0,0.233862,21.0
6,Marsabit,0.699099,7.0,2.966133,12.0,0.527179,8.0,0.207123,26.0
7,Nakuru,0.694133,8.0,3.405589,6.0,0.543407,6.0,0.401113,4.0
8,Taita taveta,0.687767,9.0,2.869853,14.0,0.523707,9.0,0.367580,10.0
9,Mombasa,0.685547,10.0,3.346246,7.0,0.516079,10.0,0.387596,7.0
10,Kwale,0.684049,11.0,2.787110,15.0,0.512756,11.0,0.226737,23.0
11,Murang'a,0.683855,12.0,3.421260,5.0,0.506693,13.0,0.260338,19.0
12,Isiolo,0.681423,13.0,2.145248,30.0,0.502854,15.0,0.244359,20.0
13,Laikipia,0.678937,14.0,2.773563,18.0,0.504765,14.0,0.264515,15.0
14,Kajiado,0.678347,15.0,3.159066,8.0,0.508877,12.0,0.370592,9.0
15,Makueni,0.677852,16.0,2.691225,21.0,0.502198,16.0,0.302017,13.0
16,Uasin gishu,0.671954,17.0,2.781739,16.0,0.495478,17.0,0.399935,5.0
17,Tharaka-nithi,0.670791,18.0,3.029893,10.0,0.480405,19.0,0.223852,24.0
18,Kisii,0.669544,19.0,2.255292,28.0,0.485727,18.0,0.378692,8.0
19,Bomet,0.664274,20.0,2.774810,17.0,0.462919,22.0,0.227665,22.0
20,Kitui,0.664244,21.0,2.742110,20.0,0.472870,20.0,0.260454,18.0
21,Siaya,0.663471,22.0,2.360076,25.0,0.469606,21.0,0.264095,16.0
22,Homa bay,0.659586,23.0,2.002660,33.0,0.460710,23.0,0.203755,27.0
23,Kilifi,0.657481,24.0,2.553197,24.0,0.456607,25.0,0.178321,32.0
24,Kakamega,0.656831,25.0,2.108839,31.0,0.459481,24.0,0.392971,6.0
25,Busia,0.656094,26.0,1.882051,37.0,0.454459,26.0,0.202129,28.0
26,Lamu,0.651899,27.0,2.206423,29.0,0.436925,28.0,0.081541,41.0
27,Narok,0.650553,28.0,1.931700,34.0,0.432156,29.0,0.192219,29.0
28,Machakos,0.649437,29.0,2.760952,19.0,0.446065,27.0,0.261406,17.0
29,Embu,0.644048,30.0,2.574251,22.0,0.422259,31.0,0.113720,37.0
30,Garissa,0.643643,31.0,2.310537,27.0,0.427037,30.0,0.285847,14.0
31,Nyamira,0.642836,32.0,1.735102,40.0,0.416806,32.0,0.184115,30.0
32,Mandera,0.642020,33.0,2.321980,26.0,0.415136,33.0,0.107999,38.0
33,Baringo,0.641170,34.0,1.921438,35.0,0.414976,34.0,0.211096,25.0
34,Kirinyaga,0.636535,35.0,2.870908,13.0,0.403603,35.0,0.121560,36.0
35,Vihiga,0.630395,36.0,1.843378,38.0,0.389884,36.0,0.134347,35.0
36,Bungoma,0.629313,37.0,1.579595,42.0,0.385894,37.0,0.158873,33.0
37,Migori,0.627134,38.0,1.594574,41.0,0.382868,38.0,0.155872,34.0
38,Turkana,0.624488,39.0,1.556233,43.0,0.363720,40.0,0.030287,46.0
39,Kericho,0.623683,40.0,2.026611,32.0,0.380621,39.0,0.183101,31.0
40,Nandi,0.618901,41.0,1.882692,36.0,0.360609,41.0,0.080365,42.0
41,Tana river,0.615047,42.0,1.405773,44.0,0.347892,42.0,0.059729,45.0
42,Meru,0.611271,43.0,2.572319,23.0,0.346354,43.0,0.087573,40.0
43,Elgeyo-marakwet,0.609765,44.0,1.369490,45.0,0.336863,44.0,0.091152,39.0
44,West pokot,0.605424,45.0,1.331486,46.0,0.324847,45.0,0.064435,44.0
45,Trans nzoia,0.602025,46.0,1.767047,39.0,0.319880,46.0,0.065100,43.0
46,Wajir,0.587989,47.0,1.180784,47.0,0.281976,47.0,0.028230,47.0

In [66]:
merged_results.to_csv("Merged Index Results.csv")